In [39]:
#Importing the libraries
import numpy as np
import pandas as pd
import tensorflow as tf

In [40]:
tf.__version__

'2.15.0'

In [41]:
#Part 1 - Data Preprocessing

In [42]:
#Importing the dataset
dataset = pd.read_csv('./Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [43]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [44]:
print(y)

[1 0 1 ... 1 1 0]


In [45]:
#Encoding categorical data

In [46]:
#Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [47]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [48]:
#One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [49]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [50]:
#Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [51]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [52]:
#Part 2 - Building the ANN

In [53]:
#Initializing the ANN
ann=tf.keras.models.Sequential()

In [54]:
#Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [55]:
#Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [56]:
#Adding the output layer
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [57]:
#Part 3 - Training the ANN

In [58]:
#Compiling the ANN
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [59]:
#Training the ANN on the Training set
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5194 - accuracy: 0.7910
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4666 - accuracy: 0.8031
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4487 - accuracy: 0.8073
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4405 - accuracy: 0.8110
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4351 - accuracy: 0.8123
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4306 - accuracy: 0.8165
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4263 - accuracy: 0.8190
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4228 - accuracy: 0.8217
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4195 - accuracy: 0.8229
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4165 - accura

In [60]:
#Part 4 - Making the predictions and evaluating the model

'''

Homework

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer?

'''

'\n\nHomework\n\nUse our ANN model to predict if the customer with the following informations will leave the bank:\n\nGeography: France\n\nCredit Score: 600\n\nGender: Male\n\nAge: 40 years old\n\nTenure: 3 years\n\nBalance: $ 60000\n\nNumber of Products: 2\n\nDoes this customer have a credit card? Yes\n\nIs this customer an Active Member: Yes\n\nEstimated Salary: $ 50000\n\nSo, should we say goodbye to that customer?\n\n'

In [61]:
#Predicting the result of a single observation
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

1/1 [==============================] - 0s 106ms/step
[[False]]


In [62]:
#Predicting the Test set results
y_pred=ann.predict(X_test)
y_pred=(y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [63]:
#Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1497   98]
 [ 184  221]]


0.859