# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

C:\Users\PC\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
tf.__version__

'2.15.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [6]:
dataset=pd.read_excel("D:\My Projects\Machine-Learning\Machine-Learning\DeepLearning\Additional_ANN\Dataset\Folds5x2_pp.xlsx")
X=dataset.iloc[:, :-1].values
y=dataset.iloc[:,-1].values

In [7]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

## Part 2 - Building the ANN

### Initializing the ANN

In [9]:
ann=tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the second hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the output layer

In [12]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [13]:
ann.compile(optimizer='adam',loss='mean_squared_error')

### Training the ANN model on the Training set

In [14]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 204.5004
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 117.5532
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 76.1754
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 55.9198
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 45.4044
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 39.5199
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 36.8817
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 34.6788
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 32.4778
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 29.0798
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 28.8940
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - loss: 27.4255

### Predicting the results of the Test set

In [15]:
y_pred=ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 807us/step
[[433.77 431.23]
 [462.42 460.01]
 [467.22 461.14]
 ...
 [474.3  473.26]
 [439.   438.  ]
 [459.39 463.28]]
